//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        public int id_delivery { get; set; }
        public string address { get; set; }
        public int delivery_type { get; set; }
        public System.DateTime transmission_date { get; set; }
        public System.DateTime arrival_date { get; set; }
        public int is_received { get; set; }
        public decimal price { get; set; }
        public int order { get; set; }
    
        public virtual delivery_type delivery_type1 { get; set; }
        public virtual ordr ordr { get; set; }
    }
}
