//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app
{
    using System;
    using System.Collections.Generic;
    
    public partial class component_install
    {
        public int id_component_install { get; set; }
        public int order_component { get; set; }
        public int work_type { get; set; }
        public string status { get; set; }
        public int employee { get; set; }
        public System.DateTime end_work_date { get; set; }
        public int warranty { get; set; }
        public int transmission_component_install { get; set; }
    
        public virtual employee employee1 { get; set; }
        public virtual order_component order_component1 { get; set; }
        public virtual work_type work_type1 { get; set; }
        public virtual transmission_component_install transmission_component_install1 { get; set; }
        public virtual warranty warranty1 { get; set; }
    }
}
