//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class course_work_Entities : DbContext
    {
        public course_work_Entities()
            : base("name=course_work_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<component> components { get; set; }
        public virtual DbSet<component_install> component_install { get; set; }
        public virtual DbSet<component_on_firm> component_on_firm { get; set; }
        public virtual DbSet<delivery> deliveries { get; set; }
        public virtual DbSet<delivery_type> delivery_type { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<firm> firms { get; set; }
        public virtual DbSet<order_component> order_component { get; set; }
        public virtual DbSet<ordr> ordrs { get; set; }
        public virtual DbSet<pc> pcs { get; set; }
        public virtual DbSet<pc_type> pc_type { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<producer> producers { get; set; }
        public virtual DbSet<transmission_component_install> transmission_component_install { get; set; }
        public virtual DbSet<warranty> warranties { get; set; }
        public virtual DbSet<work_type> work_type { get; set; }
    }
}
